### PR TITLE
Use atomic_pointer* methods when available

### PR DESCRIPTION
**Pull request by jpsamaroo**
Todo:
- [ ] Add `modify!` implementation

### CODE REVIEW

**Comment by willow-ahrens** [comment]
I'm curious, on my machine I'm noticing that the llvm approach is faster than the atomic_pointermodify approach. Do you expect to observe this as well? Do you plan to continue using this package as Julia begins to provide more atomic operations?

**Comment by vchuravy** [comment]
> I'm curious, on my machine I'm noticing that the llvm approach is faster than the atomic_pointermodify approach. Is this expected? Do you plan to continue using this package as Julia begins to provide more atomic operations?

That isn't expected... Do you have a MWE?

**Review by maleadt — APPROVED** [review]

**Comment by willow-ahrens** [comment]
Ah, that's unfortunate! It would be great if Julia had better support for atomic increment. Do we know if anything is planned for future versions?

**Comment by vchuravy** [comment]
>  Do we know if anything is planned for future versions?

I will try to find some time to update the old PR.

**Comment by jpsamaroo** [comment]
Thanks for getting this fixed up and merged! ❤️

**Comment by willow-ahrens** [comment]
Yes, thanks! I'm currently working on parallelizing Finch and this package has been integral to getting the peak performance.

**Pull request merged**
